# Create a odoo services
# In odoo volumes we need to set the path of our 
# current addons folder in local machine
# we can also define environment variables
# odoo deploy replicas are used on failure state
# odoo depends_on links 2 containers
version: "3"
services:
  odoo:
    image: odoo
    deploy:
       replicas: 3
       restart_policy:
            condition: on-failure
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - E:/gpshiring/Demos/gps.odoo.modules/src:/mnt/extra-addons   

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  nginx:
    image: nginx
    ports:
      - "8085:80"
    depends_on:
      - odoo
    volumes:
      - E:\gpshiring\Demos\odoo-docker-compose\nginx\nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  odoo-web-data:
  odoo-db-data: